app = "hijab-ul-dua-platform"

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "5000"
  NODE_ENV = "production"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[checks]
  [checks.http]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/api/setup"
    port = 5000
    timeout = "10s"
    type = "http"